# Generated by Django 5.2.7 on 2025-12-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmodel',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
