# Generated by Django 5.2.7 on 2025-12-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_applicantmodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='company.skill'),
        ),
    ]
