# Generated by Django 5.2.7 on 2025-12-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_jobrequiremenst_alter_applicantmodel_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='job_requirements',
            new_name='requirements',
        ),
    ]
