# Generated by Django 5.2.7 on 2025-12-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letter/'),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
