# Generated by Django 5.2.7 on 2025-12-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_applicantmodel_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='contact',
            field=models.CharField(),
        ),
    ]
