# Generated by Django 5.2.7 on 2025-12-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_jobmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
