# Generated by Django 5.2.7 on 2025-12-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_rename_job_requirements_jobmodel_requirements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobRequiremenst',
            new_name='JobRequirement',
        ),
    ]
