# Generated by Django 5.2.7 on 2025-12-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_rename_jobrequiremenst_jobrequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='skills',
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='requirements', to='company.jobrequirement'),
        ),
    ]
