# Generated by Django 5.2.7 on 2025-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_jobmodel_skills_alter_jobmodel_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
