# Generated by Django 5.2.7 on 2025-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_jobmodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
